from src.constants import *
import os, sys

#DEFINING ROOT_DIR_KEY FROM CONSTANTS/__INIT__.py
ROOT_DIR = ROUTE_DIR_KEY

#CONNECTING ROUTE OF DATASET WITH ROUTE_DIR_KEY/DATA_DIR/DATA_DIR_KEY
DATASET_PATH = r"c:\Users\lokes\OneDrive\Desktop\dataset\finalTrain.csv"

#DOWNLOADED DATA STORE HERE
RAW_FILE_PATH=os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY, 
CURRENT_TIME_STAMP, DATA_INGESTION_RAW_DATA_DIR,RAW_DATA_DIR_KEY)

#SPLITTED DATA TRAIN DATA STORED HERE
TRAIN_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY,
CURRENT_TIME_STAMP, DATA_INGESTION_INGESTED_DATA_DIR_KEY,TRAIN_DATA_DIR_KEY)

#SPLITTED DATA TEST DATA STORED HERE
TEST_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY,
CURRENT_TIME_STAMP, DATA_INGESTION_INGESTED_DATA_DIR_KEY,TEST_DATA_DIR_KEY)