from src.constants import TRANSFORM_TRAIN_DIR_KEY
from src.constants import DATA_TRANSFORM_DIR
from src.constants import DATA_TRANSFORMATION_PROCESSING_OBJECT
from src.constants import DATA_PREPROCESSED_DIR
from src.constants import DATA_TRANSFORMATION_ARTIFACT
from src.constants import ARTIFACT_DIR_KEY
from src.constants import *#Error
import os, sys

#DEFINING ROOT_DIR_KEY FROM CONSTANTS/__INIT__.py
ROOT_DIR = ROOT_DIR_KEY

#CONNECTING ROUTE OF DATASET WITH ROUTE_DIR_KEY/DATA_DIR/DATA_DIR_KEY
DATASET_PATH = os.path.join(ROOT_DIR, DATA_DIR, DATA_DIR_KEY)

#Data ingestion:
#DOWNLOADED DATA STORE HERE
RAW_FILE_PATH=os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY, 
                                 CURRENT_TIME_STAMP, DATA_INGESTION_RAW_DATA_DIR,RAW_DATA_DIR_KEY)

#SPLITTED DATA TRAIN DATA STORED HERE
TRAIN_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY,
                                CURRENT_TIME_STAMP, DATA_INGESTION_INGESTED_DATA_DIR_KEY,TRAIN_DATA_DIR_KEY)

#SPLITTED DATA TEST DATA STORED HERE
TEST_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_INGESTION_KEY,
                                CURRENT_TIME_STAMP, DATA_INGESTION_INGESTED_DATA_DIR_KEY,TEST_DATA_DIR_KEY)


#Data Transformation steps:
PREPROCESSING_OBJ_FILE = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_TRANSFORMATION_ARTIFACT,
                                        DATA_PREPROCESSED_DIR, DATA_TRANSFORMATION_PROCESSING_OBJECT)


TRANSFORM_TRAIN_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT, 
                                        DATA_TRANSFORM_DIR, TRANSFORM_TRAIN_DIR_KEY)

TRANSFORM_TEST_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT, 
                                        DATA_TRANSFORM_DIR,TRANSFORM_TEST_DIR_KEY)


FEATURE_ENGG_OBJ_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR_KEY, DATA_TRANSFORMATION_ARTIFACT,
                                        DATA_PREPROCESSED_DIR, 'feature_engg.pkl')